apiVersion: v1
kind: Secret
metadata:
    name: longhorn-basic-auth-users
    namespace: longhorn-system
stringData:
    users: ENC[AES256_GCM,data:sD8a+19ynOuVZNkhp7jOx3GNSs7YTA4RDfA/thEUaCshHxK/B4nCWmYDFh86qiCi6sOKoh57oJPbzN+GCg9kTkNn,iv:q/69KkRAirIA5GVHID8z0JAt51VqgrSiYptdJh3yTg4=,tag:sc/XGG0ZDm3JdJ0vTjnxWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n2utxc8aycdn5wfjsamtn3m7ha3vrsg76nkd32r0wpg4d6298c9suy7cwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTkFndFNIeWovbTMyT1li
            ZDFOQWhmM1BBOFFkaitpbzFVRmtGZ0U5NHkwCmdqeVp6SDJReE9nVk5mdjVuYmMy
            VCsyZVpyaG56YkVyWkpFdkxXRXVOSlkKLS0tIG9QelBUcGVLM2RPc3VGdmxCSDVG
            ZjlxUXIxL1pWWE9aQ2NHc2k2QUt1d28KCgDvzoyxZYWVUvhKwopmNtPAZjilYFEm
            5GieHRVY0168L43BUpvgmzyaCOXW4qVkSkVQ6Y0kGepZMuKtXdk4JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T23:31:37Z"
    mac: ENC[AES256_GCM,data:iQhp8ciPCETDmEoVA7wUg1zaDnwTPLnw7ENJzhXqrsdta5IkULXtui90o3MKe1y8EgOxNMRrWAeBi037lyJqVl78UgtBB2DzDGrO1TYu00dEtAl6obfVu1JMdvZrQQN2iJSbZJ87nxGe6lzLiHhxLYevnAzdfWnkLnK9WQAboT4=,iv:yCcgWWEikGjaXjP6ITXKr8S+3I4Viv2xI71eUAhyLw8=,tag:+7bZ5uZYCWZtpagRgRMJkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
