apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie

  template:
    metadata:
      labels:
        app: mealie

    spec:
      containers:
        - name: mealie-recipes
          image: ghcr.io/mealie-recipes/mealie:v2.8.0

          envFrom:
            - configMapRef:
                name: mealie-configmap

          ports:
            - containerPort: 9000
              protocol: TCP

      restartPolicy: Always
