apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie

  template:
    metadata:
      labels:
        app: mealie

    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:latest

          envFrom:
            - configMapRef:
                name: mealie-configmap

          ports:
            - containerPort: 9001
              protocol: TCP

      restartPolicy: Always