apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:6/FQMCIJMyAjWALXlgkYXOPyqHRsVt27Ggy9fd3jst5nkfGtWz+1/hQNCjsbyR8/HvozN1GOH3ZywGFJRhiKglCyfiYYRjou0jMKKUrxynq97n2+BUxHGo9E+b0rkJMXQHi/TezBHBCRlQ21S7sl58vAvX/CMO0V29pCadNndz7EEHFMJ1F4yTOFjdcORbjklUWC6oBhcJNGRM14DfqVn9g9ilAVTRNDNf8Y1JQVx1e3/xKDqODqSlgSG7KpKw9wujxdrc9mPaM0BR3LzRXy9/8GSiiriF8+,iv:UqXjJ/+oPQrMXpxJBY2kWDXv4JThtNvIu7kfnHlyCVE=,tag:GPuZ8sdMrt4/tmQgk/n8IQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n2utxc8aycdn5wfjsamtn3m7ha3vrsg76nkd32r0wpg4d6298c9suy7cwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORDBXWlVRYi9TcWVRVzk0
            YVdSenZyeTlLdjhhRjFrQTI2aWk2SGJpTEFrCjJkbWRYOFR3MkV3cXVUSFlJS3dS
            MkNsbUpkSEN6Y2dHb0hBblFPODZIa28KLS0tIHBtVDRkRmliVjRHdVkxZVRNNFVm
            MGpDRDNHdUNxYW0zWHpzbDkvUGh6UjgKUq+dV4yFC3j+SfTwYNWOvE/kDXn6SCcG
            PnpAZhBcNLf4VhTvKNWjJ74pq6/V1E3ZzlAtewGAef4bzYIDkxGkZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T00:05:32Z"
    mac: ENC[AES256_GCM,data:DBaU0aqRYGPsU3sBJkBkOvC8KOxYSmT2J2PfvbVzVjV8yJeVi4GwbAg00XVy4HNZE3slKk2jur9jN4Omdf7Vv/cKlk3Py6S0LG4ZSzgS4YwVO+T6+QsrVzxfXE0QQR/kCsNOOnQlQrCerwlX3kC0ZVgWwLbQ1sbYMAqt2Ilx3hQ=,iv:wg7d/naIYTTYBhiPJpO+xp3dtiK43w5RhQCXyKipQfY=,tag:G9VwYRhmlolsGd7MBx+qng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
