apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ZFtWU0FOaHM=,iv:oT16ZQADG/VnCi4Gw58TxvC6UVttkVraxz1x5qSXu48=,tag:AWQHPQSbVTSIcRjfYV5aHg==,type:str]
    user: ENC[AES256_GCM,data:44bdzWI4rz8=,iv:0xtr/lqX5pSbElYX03vfveHfMvzafvEZGBAL0p/R0sI=,tag:FOKLPRmvMHlg6nvrolm7mQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n2utxc8aycdn5wfjsamtn3m7ha3vrsg76nkd32r0wpg4d6298c9suy7cwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTllLTXpsWFRXNjBhWU0y
            RXNGUUNmTW0xbWt2d1RCdWJ1dXQvbzVwRWx3CjBiclBmTEs1WlNMSFlkVFBlMjZp
            Q3p4eUhHSC84b0x3RE45djJZMUkydVkKLS0tIHdRL2RKVkJ4OG9qVWtiQ0E2NHRE
            dktrbnVRNEhZSUdkeGR6MjI3dXFIRjAKkQcJ8q7Gs3++Gq6+RdLuwl+6mC2whQp6
            KFEzHaZWxPJGHEGH0xWwVPlenWvV9O09/+8W/FT14YNZv0pMdHqoqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T00:19:02Z"
    mac: ENC[AES256_GCM,data:T8o2Rb1CY1yHutXSyayPzIExwTSFAjmehMu9QP7opllz5o/ZCvTl9mboIBafaMTqB4Nl82lkmK9oLtUm40W0UK/HFYECMkr/Ilezp0x4FA4g+BsgFLVvrJ+tSMof1hFEMvuScFCvttz9gh4Z4CdxUBeAFDA35Gn/PFLjokBOF9Y=,iv:NAufykvNC1jnoGnLMAZHkpM1q30jJWI4Oiei8C+qHLQ=,tag:6DT55gsMCQ71OAmmw78f7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
