apiVersion: v1
data:
    password: ENC[AES256_GCM,data:iZASoXxZ6ryqYkc4A3Baoir7bqclGRZOxCpvow==,iv:9/GmL584E1hlqew8gIPoPARufh/lqDDfSAY56suQNrE=,tag:wIXS3iNWJpfq8A0kiSqOPw==,type:str]
    username: ENC[AES256_GCM,data:fAw3v6ox6BWMCbzpAcj2YBv844KaVaR8mJhvR+bV+W4=,iv:WMRamVv+WXXv/DIlMfWkcOR6c5JvGQdAX0QN/LLT4Cc=,tag:1jXgT+b9yneZIlxy0CFjFQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: alertmanager-gmail-smtp
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n2utxc8aycdn5wfjsamtn3m7ha3vrsg76nkd32r0wpg4d6298c9suy7cwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Ti9pNEozZkZPaGZsL0tI
            N29GTUhrSjYybTAzVHVZZzRPczJQbFdaYWdzCmxvS2xTRjRDWis1SFJVS0x4NGhr
            a2Z6VUNjR3IrN0NnZmt6SGlRczd6MU0KLS0tIFE3c1ZoYmZrRXFIYVpqUnhYY24x
            RGtRa0lRMzVkMGx3NUhRVkhyWi9mWXMKaTmrXLyvY1MXfdsAo76FHeOBM+WsCQgA
            w6kytkpWATuTEkYcZuUNrrwdddH/XIXxxPAgNb+urguIHcHbjel9Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-24T22:47:38Z"
    mac: ENC[AES256_GCM,data:uF6oLHRqxwIDAgDoWjDn5z8WPAvRJb+TuvZmJ2I6MPyWMRLHITWVKdiJWByyCpUgl26/Vvg7l2VIhlxTEtt8JrvqN+QIxWEy3To/8128T1wPCPz5DsHM6Jo5uIToxyT76YpfwNhNGkaFHcJRsfGePqJ0sZIM0itGgs6spXkep1o=,iv:jOdBJKD3k0rBR2VPeYyXRTXa460BhgIsxPpl25oPUD8=,tag:gqG/9YVYcbLaM0ZNdZ/5IA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
